[package]
name = "alfred-zed"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
sqlite = "0.36"

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'
opt-level = 'z'
strip = "symbols"
